DEFAULT_CATEGORIES = [
    {
        "slug": "kung_pao_chicken",
        "display_name": "宫保鸡丁",
        "keywords": [
            "宫保鸡丁 菜品",
            "kung pao chicken dish",
            "宫保鸡丁 美食",
            "宫保鸡丁 成品图",
            "宫保鸡丁 餐厅",
            "宫保鸡丁 高清",
            "kung pao chicken chinese food",
            "kung pao chicken plate",
            "spicy diced chicken with peanuts",
        ],
    },
    {
        "slug": "mapo_tofu",
        "display_name": "麻婆豆腐",
        "keywords": [
            "麻婆豆腐 菜品",
            "mapo tofu dish",
            "麻婆豆腐 美食",
            "麻婆豆腐 成品图",
            "麻婆豆腐 餐厅",
            "麻婆豆腐 高清",
            "mapo tofu chinese food",
            "mapo tofu plate",
            "sichuan mapo tofu",
        ],
    },
    {
        "slug": "dumplings",
        "display_name": "饺子",
        "keywords": [
            "饺子 菜品",
            "dumplings chinese food",
            "水饺 美食",
            "饺子 成品图",
            "饺子 高清",
            "水饺 菜品",
            "boiled dumplings chinese food",
            "jiaozi dish",
            "dumplings plate",
        ],
    },
    {
        "slug": "fried_rice",
        "display_name": "炒饭",
        "keywords": [
            "炒饭 菜品",
            "fried rice dish",
            "蛋炒饭 美食",
            "炒饭 成品图",
            "炒饭 高清",
            "蛋炒饭 菜品",
            "chinese fried rice",
            "egg fried rice plate",
            "fried rice chinese food",
        ],
    },
    {
        "slug": "sweet_and_sour_pork",
        "display_name": "糖醋里脊",
        "keywords": [
            "糖醋里脊 菜品",
            "sweet and sour pork dish",
            "糖醋里脊 美食",
            "糖醋里脊 成品图",
            "糖醋里脊 高清",
            "糖醋里脊 餐厅",
            "sweet and sour pork chinese food",
            "sweet sour pork plate",
            "gu lao rou dish",
        ],
    },
]
